Partial Silhuette: 0.070448
Partial Silhuette: 0.068522
Partial Silhuette: 0.068363
Partial Silhuette: 0.069521
Partial Silhuette: 0.064571
Partial Silhuette: 0.053099
Partial Silhuette: 0.059996
Partial Silhuette: 0.067146
Partial Silhuette: 0.072059
Partial Silhuette: 0.069307
Partial Silhuette: 0.065378
Partial Silhuette: 0.063936
Partial Silhuette: 0.064794
Partial Silhuette: 0.058439
Partial Silhuette: 0.063446
Partial Silhuette: 0.064812
Partial Silhuette: 0.044177
Partial Silhuette: 0.065298
Partial Silhuette: 0.057562
Partial Silhuette: 0.060737
Partial Silhuette: 0.067363
Partial Silhuette: 0.066508
Partial Silhuette: 0.069549
Partial Silhuette: 0.044499
Partial Silhuette: 0.056358
Partial Silhuette: 0.060841
Partial Silhuette: 0.068696
Partial Silhuette: 0.069936
Partial Silhuette: 0.057604
Partial Silhuette: 0.049983
Partial Silhuette: 0.059206
Partial Silhuette: 0.066709
Partial Silhuette: 0.065193
Partial Silhuette: 0.063464
Partial Silhuette: 0.064148
Partial Silhuette: 0.051110
Partial Silhuette: 0.055130
Partial Silhuette: 0.069301
Partial Silhuette: 0.068747
Partial Silhuette: 0.049439
Partial Silhuette: 0.071262
Partial Silhuette: 0.071841
Partial Silhuette: 0.060425
Partial Silhuette: 0.059955
Partial Silhuette: 0.061167
Partial Silhuette: 0.069603
Partial Silhuette: 0.059820
Partial Silhuette: 0.072247
Partial Silhuette: 0.057778
Partial Silhuette: 0.065155
Partial Silhuette: 0.072162
Partial Silhuette: 0.065321
Partial Silhuette: 0.054797
Partial Silhuette: 0.046219
Partial Silhuette: 0.065553
Partial Silhuette: 0.065797
Partial Silhuette: 0.066374
Partial Silhuette: 0.064212
Partial Silhuette: 0.063201
Partial Silhuette: 0.063482
Partial Silhuette: 0.066753
Partial Silhuette: 0.054183
Partial Silhuette: 0.069363
Partial Silhuette: 0.061473
Partial Silhuette: 0.072722
Partial Silhuette: 0.066516
Partial Silhuette: 0.066505
Partial Silhuette: 0.065052
Partial Silhuette: 0.068781
Partial Silhuette: 0.062115
Partial Silhuette: 0.069104
Partial Silhuette: 0.055758
Partial Silhuette: 0.068198
Partial Silhuette: 0.067340
Partial Silhuette: 0.075420
Partial Silhuette: 0.068738
Partial Silhuette: 0.062336
Partial Silhuette: 0.067288
Partial Silhuette: 0.063488
Partial Silhuette: 0.064766
Partial Silhuette: 0.064516
Partial Silhuette: 0.062085
Partial Silhuette: 0.057342
Partial Silhuette: 0.071516
Partial Silhuette: 0.068393
Partial Silhuette: 0.067284
Partial Silhuette: 0.070330
Partial Silhuette: 0.065836
Partial Silhuette: 0.069150
Partial Silhuette: 0.056109
Partial Silhuette: 0.068695
Partial Silhuette: 0.068144
Partial Silhuette: 0.068424
Partial Silhuette: 0.061464
Partial Silhuette: 0.055114
Partial Silhuette: 0.072753
Partial Silhuette: 0.067555
Partial Silhuette: 0.047235
Partial Silhuette: 0.066192
Partial Silhuette: 0.065421
Partial Silhuette: 0.075157
Partial Silhuette: 0.058529
Partial Silhuette: 0.066109
Partial Silhuette: 0.063935
Partial Silhuette: 0.055208
Partial Silhuette: 0.069527
Partial Silhuette: 0.061442
Partial Silhuette: 0.060983
Partial Silhuette: 0.063856
Partial Silhuette: 0.058065
Partial Silhuette: 0.061244
Partial Silhuette: 0.063213
Partial Silhuette: 0.073494
Partial Silhuette: 0.064739
Partial Silhuette: 0.062871
Partial Silhuette: 0.066504
Partial Silhuette: 0.079050
Partial Silhuette: 0.063571
Partial Silhuette: 0.059964
Partial Silhuette: 0.055692
Partial Silhuette: 0.068404
Partial Silhuette: 0.064498
Partial Silhuette: 0.070470
Partial Silhuette: 0.061015
Partial Silhuette: 0.060707
Partial Silhuette: 0.060943
Partial Silhuette: 0.066251
Partial Silhuette: 0.066066
Partial Silhuette: 0.070067
Partial Silhuette: 0.065238
Partial Silhuette: 0.070594
Partial Silhuette: 0.069732
Partial Silhuette: 0.061265
Partial Silhuette: 0.037623
Partial Silhuette: 0.063265
Partial Silhuette: 0.059693
Partial Silhuette: 0.063899
Partial Silhuette: 0.077947
Partial Silhuette: 0.067536
Partial Silhuette: 0.066929
Partial Silhuette: 0.041796
Partial Silhuette: 0.066955
Partial Silhuette: 0.065952
Partial Silhuette: 0.063720
Partial Silhuette: 0.065414
Partial Silhuette: 0.072827
Partial Silhuette: 0.031896
Partial Silhuette: 0.070586
Partial Silhuette: 0.067846
Partial Silhuette: 0.069109
Partial Silhuette: 0.063274
Partial Silhuette: 0.060850
Partial Silhuette: 0.048437
Partial Silhuette: 0.070865
Partial Silhuette: 0.057953
Partial Silhuette: 0.064910
Partial Silhuette: 0.065947
Partial Silhuette: 0.069259
Partial Silhuette: 0.066128
Partial Silhuette: 0.072203
Partial Silhuette: 0.067624
Partial Silhuette: 0.065564
Partial Silhuette: 0.063534
Partial Silhuette: 0.068793
Partial Silhuette: 0.073398
Partial Silhuette: 0.065264
Partial Silhuette: 0.064972
Partial Silhuette: 0.065064
Partial Silhuette: 0.058910
Partial Silhuette: 0.066168
Partial Silhuette: 0.067172
Partial Silhuette: 0.072414
Partial Silhuette: 0.062365
Partial Silhuette: 0.063603
Partial Silhuette: 0.067302
Partial Silhuette: 0.066745
Partial Silhuette: 0.065373
Partial Silhuette: 0.066243
Partial Silhuette: 0.067612
Partial Silhuette: 0.066137
Partial Silhuette: 0.056275
Partial Silhuette: 0.064004
Partial Silhuette: 0.063320
Partial Silhuette: 0.063897
Partial Silhuette: 0.056182
Partial Silhuette: 0.070188
Partial Silhuette: 0.064043
Partial Silhuette: 0.069693
Partial Silhuette: 0.062377
Partial Silhuette: 0.066971
Partial Silhuette: 0.070259
Partial Silhuette: 0.059439
Partial Silhuette: 0.064319
Partial Silhuette: 0.069811
Partial Silhuette: 0.064392
Partial Silhuette: 0.062056
Partial Silhuette: 0.068822
Partial Silhuette: 0.063090
Partial Silhuette: 0.059737
Partial Silhuette: 0.068342
16	vuelves a levantar
16	volver a  tomar
16	venirse a tomar
16	iba a entender
16	empecé a conocer
16	esté pidiéndote
16	vamos a buscar
16	vayas a pensar
16	deja contarlos
16	trato de acordarme
16	vamos a cambiar
16	vamos a arreglar
16	empezamos a dispersar
16	pudimos hacer
16	empezamos a buscar
16	empezamos a buscar
16	vino a crucificar
16	hay que recordar
16	vuelvo a recalcar
16	acabo de decir
16	acabé de mencionar
16	deben de aceptar
16	vamos a tener
16	vamos a tener
16	vuelve a cantar
16	acabo de descrestar
16	debe hacer
16	deben de tener
16	deben de maltratar
16	deben de limpiar
16	deben de lavar
16	vamos a suponer
16	vienen a vigilarlo
16	hacen fumar
16	deben de ayudar
16	fui a preguntar
16	empecé a dar
16	puse a investigar
16	vuelvas a hacer
16	pudo hacer
16	iba a decir
16	venir a buscar
16	pongo a verme
16	debo de hacer
16	pones a pensar
16	fue a conocer
16	podamos sacarles
16	vámonos hacer
16	pongo a hacer
16	vino a buscarme
16	vamos a hacerla
16	pueda apoyar
16	deberían cambiar
16	piensan volver
16	tenemos que hacernos
16	vamos a levantar
16	vamos a preocuparnos
16	íbamos a tener
16	vamos a entrarle
16	vamos a encajarnos
16	vamos a aventarnos
16	ponen a platicar
16	vas a respetar
16	vamos a tratar
16	vamos solucionarlo
16	tengo que aceptarlos
16	pongo a platicar
16	vamos a practicar
16	piensan hacer
16	piensan hacer
16	dedicando a hacer
16	viene a planchar
16	empecé a vivir
16	fui a repartirlas
16	fue dibujar
16	empecé a hacer
16	íbamos a vivir
16	iba a plasmar
16	vamos a borrar
16	vuelvo a hacer
16	acostumbro a meter
16	tratan de buscar
16	pienso terminar
16	vuelvo a hablar?
16	puedo también manejar
16	pienso echarle
16	llevo de conocerlos
16	llevo de conocerlos
16	haciendo suponer
16	podré explicar
16	empecé a andar
16	empecé a pagar
16	empecé a pagar
16	empecé a llorar
16	vayas a arrancar
16	vamos a pasar
16	vamos a hacer
16	vamos a invitarnos
16	irnos a pasear
16	empecé a vivir
16	ya tiene dicho
16	pienso yo venir
16	pongo a sacar
15	va empezando
15	va empezando
15	fui empezando
15	iban recomendando
15	va convenciendo
15	va recomendando
15	voy empezando
15	iba comentando
15	esté presentado
14	hay que saber
14	hay que ver
14	hay que saber
14	hay que ser
14	viene a ser
14	ha sido muy mentado
14	ha de ser
14	ha de ser
14	hay que ver
14	ve a ver
14	debe de ser
14	hay que revolver
14	debe de ser
14	hay que conserva
14	hay que hacer
14	hay que echarle
14	hay que tener
14	hay que saber
14	hay que ir
14	he de haber
14	ha de haber
14	hay que poner
14	he podido ir
14	hay que ir a apoyar
14	hay que ir
14	incompleta
14	debe de haber
14	debe de haber
14	hay que saber
14	hay que saber
14	hay que cargar
14	hay que desarrollar
14	ha sido ser
14	vas a desprender
14	vete a hacer
14	vas a ir
14	hay que estar
14	ha de tener
13	están como desabridos
13	andan regados
13	estábamos tan fregados
13	estuvimos arrimados
13	estábamos preparados
13	estábamos pagando
13	andábamos peleados
13	estamos casi esclavizados
13	estamos muy escasos
13	estábamos buscando
13	estar completamente pelados
13	quedan parados
13	estaríamos amolados
13	vienen armados
13	está catalogado
13	estuvieron gustando
13	estábamos en bolita ahí cotorreando
13	tener reunidos
13	estaban manoseando
13	andes manoseando
12	voy a comprar
12	voy a comprar
12	fui a comprar
12	hay que comprar
12	hay que comprar
12	iba a financiar
12	vamos a comprar
11	empezaron a entrar
11	empezaron a colonizar
11	empezaron a estar
11	empezaron a vender
11	empezó uno a buscar
11	empezó a levantarse
11	empezó a llegar
11	empezó a crecer
11	empezó a llegar
11	empiece uno a pedir
11	empieza uno a andar
11	empiezan a salir
11	empiezan a cantar
11	iba a empezar
11	empezó a portar
11	empezaron a aceptar
11	empezó a ver
11	empezaron a escarbar
11	empezaron a
11	empezaban a meterse
11	empiezan a dar
11	empezaron a meter
11	empezaron a entrar
11	empiezan a agarrar
11	empezaron a quitar
11	empezaron a agarrar
11	empezar a aprender
11	empezar a embarrar
11	empieza a estar
11	empezarle a batallar
11	comenzó a trazar
11	comienzan a agarrar
11	comienzan a amedrentarlos
11	empieza a entrar
11	comienzan a disgustar
11	comienzan uno a desvariar
11	comience uno a decir
11	comienzan a hacer
11	empezó a subir
11	empezó a llegar
11	empezó a llamar
11	empezaba a subir
11	empezaba a saber
11	empieza como que a elevar
11	empiezo a meter
11	vuelven a llamar
11	empezó a golpear
11	empezó a decir
11	empezó a agarrar
11	empiezo a platicar
11	empiezan a platicar
11	vuelve a agarrar
11	vuelve a agarrar
11	empezó a decir
11	empiezan a hacer
10	estoy vendiendo
10	están metiendo
10	fue agrandando
10	este agarrando
10	estén golpeando
10	va uno ya creciendo
10	andaba yo buscando
10	estuvo viviendo
10	andaban persiguiendo
10	anda buscando
10	teníamos pagando
10	estaba yo diciendo
10	anduve rodando
10	andaba yo vendiendo
10	fui pasando
10	fuimos pasando
10	estoy yo diciendo
10	andaban buscando
10	van metiendo
10	van contagiando
10	sigue celebrando
10	sigue luchando
10	andarle quitando
10	está repartiendo
10	están anunciando
10	va dando
10	estoy diciendo
10	estuvieran ganando
10	estamos viviendo
10	sigue criando
10	ha ido progresando
10	estamos constatando
10	ha ido progresando
10	ha ido progresando
10	sigo practicando
10	vamos a seguir viviendo
10	está cuidando
10	están pasando
10	fui metiendo
10	fui aprendiendo
10	está ella acomodando
10	iban haciendo
10	estaba saliendo
10	fui aprendiendo
10	estoy juntando
10	estaban robando
10	estaba yo hablando
10	anduvieron llevándose
10	estaba yo esperando
10	estaba comprando
10	estar cuidando
10	fui recorriendo
10	estar este metiéndose
10	estaba viendo
10	estoy viendo
10	vas sabiendo
10	estaba dando
10	andas tomando
10	estoy cambiando
10	fui dedicando
10	estoy viendo
10	andamos buscando
10	sigues diciendo
10	salen sobrando
10	vas formando
10	sigo jugando
10	vas viendo
10	vas pensando
10	está ampliando
10	están haciendo
10	va dando
10	fui aprendiendo
10	voy saliendo
10	voy haciendo
10	estamos ahí amotinando
10	está viniendo
10	estuvimos insistiendo
10	estaba manejando
10	estaba manejando
10	está echando
10	va componiendo
10	vamos a seguir viviendo
10	se va a ir urbanizando
10	se va a ir urbanizando
10	va a ir este componiendo
10	iban diciendo
10	fue manejando
10	andar pagando
10	sigan pagando
10	va llegando
10	van viendo
10	va viendo
10	va entrando
10	vaya aceptando
10	va haciendo
10	va viendo
10	vamos viendo
10	estaban viviendo
10	fueron aplacando
10	va haciendo
10	están viendo
10	están viendo
10	van haciendo
10	van siendo
10	van traumando
10	va uno traumando
10	van viendo
10	van viendo
10	van este guiando
10	vas viendo
10	va quedando
10	estoy un rato conviviendo
10	voy dejando
10	vayan acostumbrando
10	estamos dedicando
10	ido desenvolviendo
10	ido practicando
10	ido aprendiendo
10	fui aprendiendo
10	piensa seguir estudiando
10	fui descubriendo
10	fue llegando
10	fue quedando
10	fui dando
10	fui desarrollando
10	fue llamando
10	fui agarrando
10	fueron llamando
10	fui elaborando
10	fui compartiendo
10	fui viendo
10	fuera creando
10	estuviera deslizando
10	estaba desperdiciando
10	pasaba imaginando
10	pasaba dibujando
10	iba explicando
10	vaya dando
10	vaya agarrando
10	vaya quedando
10	vaya quedando
10	esté atendiendo
10	vas haciendo
10	estoy haciendo
10	estoy viendo
10	está guiando
10	terminan matizando
10	están pagando
10	va dando
10	está quedando
10	está convenciendo
10	voy rebajando
10	voy haciendo
10	están haciendo
10	están haciendo
10	están hablando
10	están platicando
10	piensa seguir estudiando
10	voy tomando
10	voy haciendo
10	estoy batallando
10	estoy haciendo
10	está fabricando
10	vas rellenando
10	vas deslizando
10	vas corriendo
10	vas poniendo
10	vas corriendo
10	vamos viendo
10	termina gustando
10	salgo perdiendo
10	está labrando
10	está pirateando
10	seguir estudiando
10	estar haciendo
10	estar atendiendo
10	fui pagando
10	fue corriendo
10	estuve manteniendo
10	iba contando
10	iba pasando
10	estaba negando
10	estaba escapando
10	estaban borrando
10	estaban borrando
10	estaba volteando
10	iba abriendo
10	iba pasando
10	iba frenando
10	quedaban viendo
10	estaba haciendo
10	iba cotorreando
10	iba poniendo
10	quedaba viendo
10	iba manejando
10	íbamos llegando
10	estamos levantando
10	estamos este fincando
10	estás pasando
10	está este asaltando
10	voy a estar bajando
10	vengo caminando
10	está marcando
10	va subiendo
10	van apretando
10	estás cobrando
10	voy a estar diciendo
10	voy a estar viendo
10	estar bajando
10	andarlo buscando
10	estar dedeando
10	estuve velando
10	salió sobrando
10	salió volando
10	seguí estudiando
10	estaban buscando
10	iba llegando
10	iba llegando
10	venía siendo
10	seguía haciendo
10	seguíamos viviendo
10	seguía estudiando
10	voy metiendo
10	está despegando
10	estoy echando
10	está/ despegando
10	está despegando
10	anda esperando
10	está grabando
10	estoy haciendo
10	estoy viendo
10	están sirviendo
10	están tomando
10	están cobrando
10	ando cambiando
10	están invirtiendo
10	anda pidiendo
10	están haciendo
10	estamos hablando
10	estamos hablando
10	están componiendo
10	estar limpiando
10	vendrían siendo
10	vendrían siendo
9	volverte a meter
9	van a meter
9	van a meter
9	iban dizque a pescar
9	iban a bañar
9	acaban de echar
9	fueron a echar
9	van a comer
9	iba a traerle mandados
9	iba a limpiarle
9	iba a barrerle
9	llegábamos a juntar
9	vamos a comer
9	llegaba a ir
9	iban a hacer
9	fuimos a vivir
9	iba yo a sobrevivir
9	fuimos a vivir
9	había yo acabado de pagar
9	fuera salir
9	van a pagar
9	van a hacer
9	fueron a pedir
9	ha dado por ir a abrirlos
9	llegué a ocupar
9	iba yo por ahí a buscar
9	vamos a salir
9	vino a morir
9	ir a visitar
9	acaba de pasar
9	pasaba la gente comiendo eso
9	van a estar
9	iba a dar
9	deben de estar
9	van a decir
9	iban a nacer
9	van a salir
9	van a salir
9	van a nacer
9	vamos a ver
9	acabo de sacar
9	deja ni tocar
9	dan a amarrar
9	ponía a tirar
9	vienen a barrer
9	llega uno a cobrar
9	llegan a tomar
9	llegaron a romper
9	fue a vendar
9	van a meter
9	iba a armar
9	van a venir
9	podía yo ni ir a comer
9	podía yo dormir
9	acababa yo de chocar
9	echaban a correr
9	metiéndose a romper
9	debe uno de tener
9	alcanzó a aventar
9	echó a correr
9	iba yo a hacer
9	ibas a tomar
9	ponen unas señoras a vender
9	metes a tomar
9	venía a dar
9	iban a tocarle
9	vamos a ver
9	dejé de tomar
9	dejar de tomar
9	iba a jugar
9	iba a jugar
9	llegó a entregar
9	ve a ayudarle
9	iban a recibir
9	iban a tener
9	iban a crecer
9	iba a ser
9	vienen a visitar
9	ibas a agarrar
9	debo de tener
9	llegó a vivir
9	dejaron de jugar
9	vamos a jugar
9	llegamos a ganar
9	llegamos a ganar
9	van a casar
9	llego a dejar
9	llego a morir
9	vas a hacer
9	darle a ganar
9	llegase a ir
9	fui a ver
9	llega a haber
9	llega a ver
9	lleguen a las de a hacer fraude
9	iban a tener
9	iban a llegar
9	llegué a ver
9	fueras a apuntar
9	iba a manejar
9	íbamos a estar este pagando
9	iban a hacer
9	vamos a ver
9	venía a verlos
9	llegaba a ver
9	llegué a dar
9	llegas a casar
9	se pongan ustedes a merendar
9	pasaron a amolar
9	iba a quedar
9	pasaron a dar
9	vamos a comer
9	van a ayudar
9	viene a lavar
9	iba a ser
9	iba a entrar
9	iba a sostener
9	iba a echar
9	iba a apoyar
9	iban a ir
9	iban a cargar
9	podía desempeñar
9	llegar a ser
9	llega a salir
9	llego a dar
9	vas a partir
9	vas a hacer
9	ir a cobrar
9	terminar de labrar
9	habíamos ido a comprar
9	vino a vivir
9	fue a vivir
9	fuiste a comer
9	fui a comer
9	fui a comer
9	acaba de entrar
9	iba a visitar
9	pasaba a visitar
9	iban a dar
9	iba a vender
9	vayas a comer
9	vamos a salir
9	vamos a comer
9	vamos a comer
9	vas a meter
9	vamos a dar
9	vamos a ir
9	vamos a ir
9	han de cobrar
9	van a parar
9	van a decir
9	van a parar
9	vamos a dar
9	van a estar
9	vas a traer
9	ir a acostar
9	irnos a comer
9	llegado a ir
9	vino a ver
9	íbamos a comer
9	van a estar
9	vamos a ver
9	van a venir
9	vamos a ver
9	se debe de ganar
8	va a venirse
8	va a pertenecer
8	volvieron a regresar
8	volvía a regresar
8	va a hacer
8	va a cuidar
8	va a platicar
8	va a hacer
8	va a haber
8	va a tener
8	va a venir
8	va a ser
8	va a preguntar
8	va a luchar
8	va a ir
8	va a ser
8	va a ser
8	va a llevar
8	va a convencer
8	va a quedar
8	va a terminar
8	va a quedar?
8	va a quedar
8	va a quedar
8	voy a  regresar
8	va a cumplir
8	va a decir
8	va a agarrar
8	va a cumplir
8	va a salir
8	va a ser
8	va a sacar
8	va a pasar
8	va a estar
8	va a costar
8	va a dar
7	poder tomar
7	poder aletear
7	poder este dormir
7	poderme defender
7	poderla hacer
7	poder cobrar
7	poderlo mostrar
7	poder tomar
7	poder mover
7	poder pagar
7	poderme sostener
7	poderlo quitar
6	poder trabajar
6	iba a trabajar
6	podíamos trabajar
6	ponía a trabajar
6	vámonos a trabajar
6	entré a trabajar
6	podía trabajar
6	fui a trabajar
6	entré a trabajar
6	empecé yo a trabajar
6	empecé a trabajar
6	sigue trabajando
6	siguen trabajando
6	siguen trabajando
6	empiezan a trabajar
6	está trabajando
6	está trabajando
6	hacen trabajar
6	sigo trabajando
6	hay que trabajar
6	estoy trabajando
6	estoy todavía trabajando
6	llegué a trabajar
6	iba a trabajar
6	han llegado a trabajar
6	empecé a trabajar
6	pude trabajar
6	entré a trabajar
6	había que trabajar
6	empiezo a trabajar
6	estás trabajando
6	estoy trabajando
6	están trabajando
6	están trabajando
6	voy trabajando
6	estoy trabajando
6	entrar a trabajar
6	iba a trabajar
6	iba a trabajar
6	empezó a trabajar
6	empecé a trabajar
5	puedes ver
5	puedes viajar
5	puede haber
5	puedan vender
5	puedan vender
5	pueda ser
5	podía darles
5	pueden vivir
5	podían vivir
5	podía yo sobrevivir
5	puede ser
5	puede ser
5	puede ser
5	puede ser
5	puede ser
5	puede fallar
5	puede subsistir
5	puede decir
5	pueden estar
5	pueden ver
5	puede ser
5	puede uno ni acercar
5	puede haber
5	puede haber
5	puede descifrar
5	puede uno sacar
5	tiene almacenado
5	puede sacar
5	podían decir
5	pueden pegar
5	puedes ni pasar
5	puede pasar
5	pueden cometer
5	puedes hacer
5	puede vernos
5	pueden vernos
5	podían hacer
5	pueden adaptar
5	pueden ocupar
5	podía jugar
5	podemos practicar
5	podía hacer
5	podía hacer
5	podía hacer
5	podía decorar
5	podía rotular
5	pueda hacer
5	pueda crear
5	puedo fabricar
5	puede decir
5	puede decir
5	puedes crear
5	puedes hacer
5	podemos poner
5	puedes usar
5	puedes usar
5	puede decir
5	puede decir
5	podría hacer
5	podía hacer
5	puedes entrar
5	puedes entrar
5	puedes vivir
5	puedes pagar
5	puedes pasar
5	puedes salir
5	puedes cargar
5	puede cobrar
5	puedes controlar
5	podían salir
5	podía subir
5	puedes hacer
5	pueden hacer
5	pueden sacar
5	pueden sacar
5	puede haber
4	está criado
4	esté encerado
4	venirse a emborrachar
4	estaba alquilado
4	anden paseando
4	dejaban dormir
4	metí a dormir
4	esta completamente abandonado
4	quedado dormido
4	quedabas dormido
4	está muy pesado
4	está este durmiendo
4	está durmiendo
4	está pensado
4	tengo pensado
4	estoy ocupado
4	estaba uno dormido
4	está retirado
4	lleve hecho
4	quedo agachado
4	quedo callado
4	quedó deshecho
4	andaba paseando
4	sale perjudicado
4	está golpeado
4	andan paseando
4	estuvo pesado
3	puedas vivir
3	podía moverme
3	podía decírselo
3	puedo decir
3	puedo hacer
3	puedo hacer
3	puedo hacer
3	puedes preguntarme
3	puedo correrlos
3	podría yo decirte
3	puedo decir
3	puedo decirte
3	podría yo decir
3	puedo yo decir
3	puedo decirlo
3	puedo meterme
3	puedo salir
3	podíamos agarrar
3	podías platicar
3	piensas ganarle
3	puedo hacerlo
3	pasó decirte
3	puedo conseguir
3	puedo pagar
3	puedo pagar
3	puedo hacer
3	podría decir
3	podría decir
3	puedo denunciar
3	puedo agarrar
3	puedo abrazar
3	dejarte agarrar
3	puedo atender
3	puede aguantar
3	puedo decir
3	puedo ir
2	tienes que tirar
2	tienes que salir
2	tenías que bajar
2	tiene uno que dar
2	tiene que ir
2	teníamos que comer
2	voy a quitarle
2	tengo que buscar
2	tiene uno que hacer
2	tienen que vivir
2	tiene que ser
2	tengo que ir
2	tienen que entrar
2	tenía uno que surtir
2	debe de quitar
2	tengo que sacar
2	tengo que pintar
2	tuve que arrancar
2	tenía que estar
2	tenido que arreglar
2	tiene que estar
2	dejaba yo salir
2	alcancé a quitar
2	fue a quedar
2	tiene que sufrir
2	tenían que tener
2	tenía que haber
2	tiene que buscar
2	tienes que buscar
2	tenemos que pagar
2	tienes que ir
2	tiene uno que andar
2	tengo que sacarle
2	tenían que ir
2	tenía que estar
2	teníamos que estar
2	hay que desalojar
2	tuvo que orillar
2	tuvo que entrar
2	tuvo que entrarle
2	tenían que pues llegar
2	tuvieron que entrarle
2	tenían que ir
2	tenía que ir
2	tiene que aventar
2	tiene uno que tomar
2	tuvimos que ir
2	van a quitar
2	tendrá qué ser
2	tenía yo que sacar
2	vas a querer
2	teníamos que hacer
2	tuvo que darse
2	tuve que aplanar
2	teníamos que descubrir
2	tenías pensado
2	tenían que quedar
2	tenía que hacer
2	tenía que [estar]
2	tenía que salirle
2	tenía que disminuir
2	tenía que dar
2	tenga que ver
2	tiene nada que ver
2	tienes que encontrarle
2	tienes que saber
2	va querer
2	tengo que llevar
2	tengo que hacer
2	tiene que darse
2	tiene que convencer
2	vas a querer
2	tengo que lucirme
2	tengo que buscarle
2	tener que llevar
2	tenías que pagar
2	tenías que este dar
2	tenía que pagar
2	tenía que pagar
2	iban a quitar
2	tenía que bajar
2	tienes que llevar
2	dejar salir
2	tienes que meterte
2	tenemos que pagar
2	tenemos que dar
2	deja quito
2	tienen que poner
2	tiene que cambiar
2	tengo que cuidar
2	tuvieron que coser
2	tenía que/ lavar
2	tenía que entrar
2	hay que guardar
2	tienen que pagar
2	tiene que dar
2	tengo que salir
2	tienen que entregar
2	tienen que ser
1	voy a dar
1	voy a decir
1	voy a decir
1	voy a correrlos
1	voy a decir
1	voy a poner
1	voy a pedir
1	voy a comentar
1	voy a cantar
1	voy a ver
1	voy a hacer
1	voy a dejar
1	voy a regalar
1	voy a leer
1	voy a dar
1	voy a seguir
1	voy a pagar
1	voy a pagar
1	voy a pagar
1	voy a pagar
1	voy a salir
1	voy a hacer
1	voy a acabar
1	voy a ir
1	voy a este hacer
1	voy a vender
1	voy a vender
1	voy a esperar
1	voy a jugar
1	voy a hacer
1	voy a poner
1	voy a estar
1	voy a reprochar
1	voy a ir
1	voy a hacer
1	voy a hacer
1	voy a ser
1	voy a decir
1	voy a practicar
1	voy a practicar
1	voy a tener
1	voy a cobrar?
1	voy a llevar
1	voy a terminar
1	voy a echarme
1	voy a tener
1	voy a empezar
1	voy a amarrar
1	voy a meter
1	voy a demostrar
1	voy a asaltar
1	voy a bajar
1	voy a bajar
1	voy a soltar
1	voy a ir a acostar
1	voy a ir
1	voy a [comer
1	voy a soltar
1	voy a dejar
1	voy a decir
1	voy a componer
1	voy a pagar
0	van creciendo
0	se van este fortaleciendo
0	hay que fortalecer
0	van fortaleciendo
Silhouette Coefficient: 0.079
Number of clusters: 17

