Partial Silhuette: 0.072482
Partial Silhuette: 0.085286
Partial Silhuette: 0.075201
Partial Silhuette: 0.079580
Partial Silhuette: 0.074066
Partial Silhuette: 0.085226
Partial Silhuette: 0.087884
Partial Silhuette: 0.087078
Partial Silhuette: 0.086912
Partial Silhuette: 0.079414
Partial Silhuette: 0.076197
Partial Silhuette: 0.082067
Partial Silhuette: 0.072927
Partial Silhuette: 0.083726
Partial Silhuette: 0.089240
Partial Silhuette: 0.077611
Partial Silhuette: 0.085654
Partial Silhuette: 0.080667
Partial Silhuette: 0.066450
Partial Silhuette: 0.074643
Partial Silhuette: 0.080211
Partial Silhuette: 0.067975
Partial Silhuette: 0.088224
Partial Silhuette: 0.076605
Partial Silhuette: 0.065960
Partial Silhuette: 0.078202
Partial Silhuette: 0.090080
Partial Silhuette: 0.084042
Partial Silhuette: 0.084117
Partial Silhuette: 0.091198
Partial Silhuette: 0.081107
Partial Silhuette: 0.080073
Partial Silhuette: 0.072124
Partial Silhuette: 0.077498
Partial Silhuette: 0.071971
Partial Silhuette: 0.077361
Partial Silhuette: 0.069815
Partial Silhuette: 0.071109
Partial Silhuette: 0.075357
Partial Silhuette: 0.080441
Partial Silhuette: 0.079303
Partial Silhuette: 0.073517
Partial Silhuette: 0.082426
Partial Silhuette: 0.066590
Partial Silhuette: 0.078914
Partial Silhuette: 0.082348
Partial Silhuette: 0.079090
Partial Silhuette: 0.071284
Partial Silhuette: 0.076292
Partial Silhuette: 0.090159
Partial Silhuette: 0.067948
Partial Silhuette: 0.086702
Partial Silhuette: 0.081508
Partial Silhuette: 0.077786
Partial Silhuette: 0.068344
Partial Silhuette: 0.074305
Partial Silhuette: 0.074464
Partial Silhuette: 0.069740
Partial Silhuette: 0.087393
Partial Silhuette: 0.066058
Partial Silhuette: 0.074986
Partial Silhuette: 0.087342
Partial Silhuette: 0.083949
Partial Silhuette: 0.084776
Partial Silhuette: 0.074314
Partial Silhuette: 0.073340
Partial Silhuette: 0.085525
Partial Silhuette: 0.074855
Partial Silhuette: 0.077316
Partial Silhuette: 0.082625
Partial Silhuette: 0.079639
Partial Silhuette: 0.089063
Partial Silhuette: 0.076901
Partial Silhuette: 0.062978
Partial Silhuette: 0.080094
Partial Silhuette: 0.073963
Partial Silhuette: 0.086073
Partial Silhuette: 0.073582
Partial Silhuette: 0.074856
Partial Silhuette: 0.079011
Partial Silhuette: 0.073165
Partial Silhuette: 0.084660
Partial Silhuette: 0.093230
Partial Silhuette: 0.067519
Partial Silhuette: 0.090041
Partial Silhuette: 0.064736
Partial Silhuette: 0.083945
Partial Silhuette: 0.067952
Partial Silhuette: 0.080105
Partial Silhuette: 0.076039
Partial Silhuette: 0.080422
Partial Silhuette: 0.061953
Partial Silhuette: 0.077350
Partial Silhuette: 0.092147
Partial Silhuette: 0.068799
Partial Silhuette: 0.076067
Partial Silhuette: 0.076849
Partial Silhuette: 0.082785
Partial Silhuette: 0.085765
Partial Silhuette: 0.067674
Partial Silhuette: 0.081597
Partial Silhuette: 0.080662
Partial Silhuette: 0.062110
Partial Silhuette: 0.081452
Partial Silhuette: 0.077162
Partial Silhuette: 0.075748
Partial Silhuette: 0.085779
Partial Silhuette: 0.077140
Partial Silhuette: 0.084419
Partial Silhuette: 0.079581
Partial Silhuette: 0.085569
Partial Silhuette: 0.075095
Partial Silhuette: 0.081941
Partial Silhuette: 0.070312
Partial Silhuette: 0.067258
Partial Silhuette: 0.084347
Partial Silhuette: 0.059050
Partial Silhuette: 0.079023
Partial Silhuette: 0.083487
Partial Silhuette: 0.069736
Partial Silhuette: 0.084855
Partial Silhuette: 0.070863
Partial Silhuette: 0.078542
Partial Silhuette: 0.079299
Partial Silhuette: 0.086574
Partial Silhuette: 0.084172
Partial Silhuette: 0.063923
Partial Silhuette: 0.080714
Partial Silhuette: 0.079690
Partial Silhuette: 0.072701
Partial Silhuette: 0.073901
Partial Silhuette: 0.061016
Partial Silhuette: 0.082278
Partial Silhuette: 0.078557
Partial Silhuette: 0.073498
Partial Silhuette: 0.074215
Partial Silhuette: 0.075096
Partial Silhuette: 0.080410
Partial Silhuette: 0.067271
Partial Silhuette: 0.066721
Partial Silhuette: 0.076324
Partial Silhuette: 0.070512
Partial Silhuette: 0.063927
Partial Silhuette: 0.073075
Partial Silhuette: 0.084257
Partial Silhuette: 0.063882
Partial Silhuette: 0.082746
Partial Silhuette: 0.077141
Partial Silhuette: 0.082298
Partial Silhuette: 0.069351
Partial Silhuette: 0.076222
Partial Silhuette: 0.067195
Partial Silhuette: 0.076926
Partial Silhuette: 0.056563
Partial Silhuette: 0.077076
Partial Silhuette: 0.081374
Partial Silhuette: 0.073999
Partial Silhuette: 0.071538
Partial Silhuette: 0.082560
Partial Silhuette: 0.076562
Partial Silhuette: 0.075916
Partial Silhuette: 0.078315
Partial Silhuette: 0.081329
Partial Silhuette: 0.087377
Partial Silhuette: 0.080042
Partial Silhuette: 0.076383
Partial Silhuette: 0.077870
Partial Silhuette: 0.079849
Partial Silhuette: 0.070574
Partial Silhuette: 0.084152
Partial Silhuette: 0.084284
Partial Silhuette: 0.066047
Partial Silhuette: 0.068464
Partial Silhuette: 0.070514
Partial Silhuette: 0.069389
Partial Silhuette: 0.080475
Partial Silhuette: 0.084598
Partial Silhuette: 0.089538
Partial Silhuette: 0.079224
Partial Silhuette: 0.063823
Partial Silhuette: 0.071675
Partial Silhuette: 0.081657
Partial Silhuette: 0.087973
Partial Silhuette: 0.080063
Partial Silhuette: 0.071546
Partial Silhuette: 0.083849
Partial Silhuette: 0.088318
Partial Silhuette: 0.081068
Partial Silhuette: 0.084187
Partial Silhuette: 0.077994
Partial Silhuette: 0.085328
Partial Silhuette: 0.082131
Partial Silhuette: 0.082764
Partial Silhuette: 0.084383
Partial Silhuette: 0.060996
Partial Silhuette: 0.084557
Partial Silhuette: 0.072400
Partial Silhuette: 0.080694
Partial Silhuette: 0.066343
Partial Silhuette: 0.066791
16	puedes ver
16	puedes viajar
16	poder tomar
16	puede haber
16	poder trabajar
16	podíamos trabajar
16	puedan vender
16	puedan vender
16	puedas vivir
16	podía moverme
16	podía decírselo
16	pueda ser
16	puedo hacer
16	puedo hacer
16	puedo hacer
16	puedes preguntarme
16	podía darles
16	pueden vivir
16	puedo correrlos
16	podían vivir
16	puede ser
16	puede ser
16	puede ser
16	puede ser
16	puede ser
16	podía trabajar
16	pudimos hacer
16	puede fallar
16	puede subsistir
16	puede decir
16	pueden estar
16	pueden ver
16	debe hacer
16	poder aletear
16	puede ser
16	deja ni tocar
16	puede haber
16	puede haber
16	dejaban dormir
16	hacen fumar
16	puede descifrar
16	puede sacar
16	puedo salir
16	podíamos agarrar
16	pudo hacer
16	podían decir
16	poderme defender
16	pueden pegar
16	poderla hacer
16	puedes ni pasar
16	puede pasar
16	podamos sacarles
16	poder cobrar
16	pueden cometer
16	puedes hacer
16	puedo hacerlo
16	pueda apoyar
16	deberían cambiar
16	piensan volver
16	puede vernos
16	pueden vernos
16	podían hacer
16	vamos solucionarlo
16	tener reunidos
16	pueden adaptar
16	pueden ocupar
16	piensan hacer
16	piensan hacer
16	podía jugar
16	podemos practicar
16	pude trabajar
16	podía hacer
16	podía hacer
16	podía hacer
16	podía desempeñar
16	podía decorar
16	podía rotular
16	lleve hecho
16	pueda hacer
16	pueda crear
16	puedo fabricar
16	puede decir
16	puedo conseguir
16	puedo también manejar
16	puede decir
16	puedes crear
16	puedo pagar
16	puedo pagar
16	puedo hacer
16	puedes hacer
16	podemos poner
16	puedes usar
16	puedes usar
16	puede decir
16	puede decir
16	poderlo mostrar
16	poder tomar
16	podré explicar
16	podría decir
16	podría hacer
16	podría decir
16	podía hacer
16	puedes entrar
16	puedes entrar
16	puedes vivir
16	puedes pagar
16	puedes pasar
16	puedo denunciar
16	puedes salir
16	puedes cargar
16	puede cobrar
16	puedes controlar
16	puedo agarrar
16	puedo abrazar
16	poder mover
16	poder pagar
16	poderme sostener
16	poderlo quitar
16	dejarte agarrar
16	podían salir
16	podía subir
16	puedes hacer
16	puedo atender
16	puede aguantar
16	puedo ir
16	pueden hacer
16	pueden sacar
16	pueden sacar
16	puede haber
15	tiene uno que dar
15	va uno ya creciendo
15	tiene uno que hacer
15	tenía uno que surtir
15	puede uno ni acercar
15	puede uno sacar
15	debe uno de tener
15	tiene uno que andar
15	tiene uno que tomar
15	comience uno a decir
14	puedo decir
14	andaba yo buscando
14	podría yo decirte
14	puedo decir
14	podía yo sobrevivir
14	puedo decirte
14	estaba yo diciendo
14	andaba yo vendiendo
14	podría yo decir
14	puedo yo decir
14	estoy yo diciendo
14	puedo decirlo
14	puedo meterme
14	estaba yo hablando
14	estaba yo esperando
14	podía yo dormir
14	dejaba yo salir
14	he podido ir
14	pienso echarle
14	tengo que lucirme
14	tienes que meterte
14	puedo decir
14	pienso yo venir
13	iban haciendo
13	iban diciendo
13	fue llegando
13	iban recomendando
13	iba explicando
13	iba contando
13	iba pasando
13	iba abriendo
13	iba pasando
13	iba frenando
13	iba cotorreando
13	iba poniendo
13	iba manejando
13	íbamos llegando
13	iba llegando
13	iba llegando
13	iba comentando
12	están como desabridos
12	están metiendo
12	andan regados
12	estén golpeando
12	sigue celebrando
12	sigue luchando
12	sigue trabajando
12	siguen trabajando
12	siguen trabajando
12	están anunciando
12	hacen trabajar
12	sigue criando
12	están pasando
12	quedan parados
12	estaban robando
12	vienen armados
12	salen sobrando
12	están haciendo
12	sigan pagando
12	estuvieron gustando
12	estaban viviendo
12	fueron aplacando
12	están viendo
12	están viendo
12	piensa seguir estudiando
12	fueron llamando
12	terminan matizando
12	están pagando
12	están haciendo
12	están haciendo
12	están hablando
12	están platicando
12	están trabajando
12	piensa seguir estudiando
12	están trabajando
12	seguir estudiando
12	estaban manoseando
12	andan paseando
12	estaban buscando
12	están sirviendo
12	están tomando
12	están cobrando
12	están invirtiendo
12	están haciendo
12	están componiendo
11	teníamos pagando
11	fui pasando
11	fuimos pasando
11	fui metiendo
11	fui aprendiendo
11	fui aprendiendo
11	fui recorriendo
11	fui dedicando
11	fui aprendiendo
11	fui aprendiendo
11	pasó decirte
11	fui descubriendo
11	fui dando
11	fui desarrollando
11	fui agarrando
11	fui empezando
11	fui elaborando
11	fui compartiendo
11	fui viendo
11	fui pagando
11	estuve velando
11	seguí estudiando
10	andaban persiguiendo
10	anda buscando
10	anduve rodando
10	andábamos peleados
10	andaban buscando
10	andarle quitando
10	anden paseando
10	quedado dormido
10	quedabas dormido
10	podías platicar
10	vas sabiendo
10	andas tomando
10	andamos buscando
10	vámonos hacer
10	vas formando
10	piensas ganarle
10	vas viendo
10	vas pensando
10	tengo pensado
10	voy saliendo
10	voy haciendo
10	andar pagando
10	vamos viendo
10	vas viendo
10	voy dejando
10	ido desenvolviendo
10	ido practicando
10	ido aprendiendo
10	tenías pensado
10	vas haciendo
10	voy rebajando
10	voy haciendo
10	voy tomando
10	voy haciendo
10	voy trabajando
10	vas rellenando
10	vas deslizando
10	vas corriendo
10	vas poniendo
10	vas corriendo
10	vamos viendo
10	termina gustando
10	salgo perdiendo
10	voy empezando
10	andaba paseando
10	andes manoseando
10	estás pasando
10	vengo caminando
10	estás cobrando
10	andarlo buscando
10	voy metiendo
10	anda esperando
10	ando cambiando
10	anda pidiendo
9	fue agrandando
9	estuvo viviendo
9	fuera salir
9	estaba alquilado
9	estuvieran ganando
9	estaba saliendo
9	anduvieron llevándose
9	estaba comprando
9	estaba viendo
9	estaba dando
9	estaba uno dormido
9	estaba manejando
9	estaba manejando
9	fue manejando
9	incompleta
9	fue dibujar
9	fue quedando
9	fue llamando
9	fuera creando
9	estuviera deslizando
9	estaba desperdiciando
9	pasaba imaginando
9	pasaba dibujando
9	quedo agachado
9	quedo callado
9	fue corriendo
9	quedó deshecho
9	estuve manteniendo
9	estaba negando
9	estaba escapando
9	estaban borrando
9	estaban borrando
9	estaba volteando
9	quedaban viendo
9	estaba haciendo
9	quedaba viendo
9	sale perjudicado
9	estuvo pesado
9	salió sobrando
9	salió volando
9	venía siendo
9	seguía haciendo
9	seguía estudiando
9	vendrían siendo
9	vendrían siendo
8	voy a comprar
8	voy a comprar
8	vuelves a levantar
8	volverte a meter
8	venirse a emborrachar
8	iban dizque a pescar
8	empecé a conocer
8	llegábamos a juntar
8	vámonos a trabajar
8	voy a dar
8	voy a decir
8	vamos a buscar
8	vamos a comer
8	voy a quitarle
8	vayas a pensar
8	voy a decir
8	voy a correrlos
8	voy a decir
8	fuimos a vivir
8	iba yo a sobrevivir
8	fuimos a vivir
8	entré a trabajar
8	voy a poner
8	voy a pedir
8	vamos a cambiar
8	vamos a arreglar
8	empezamos a dispersar
8	iba yo por ahí a buscar
8	fui a trabajar
8	entré a trabajar
8	empecé yo a trabajar
8	empecé a trabajar
8	empezamos a buscar
8	empezamos a buscar
8	vamos a salir
8	voy a comentar
8	vuelvo a recalcar
8	voy a cantar
8	vamos a seguir viviendo
8	voy a ver
8	vamos a tener
8	vamos a tener
8	voy a hacer
8	voy a dejar
8	vamos a suponer
8	vamos a ver
8	voy a regalar
8	voy a leer
8	voy a dar
8	metí a dormir
8	fui a preguntar
8	empecé a dar
8	puse a investigar
8	vuelvas a hacer
8	fui a comprar
8	voy a seguir
8	voy a pagar
8	voy a pagar
8	voy a pagar
8	voy a pagar
8	llegué a trabajar
8	venir a buscar
8	podía yo ni ir a comer
8	pongo a verme
8	alcancé a quitar
8	iba yo a hacer
8	ibas a tomar
8	metes a tomar
8	vamos a ver
8	voy a salir
8	voy a hacer
8	pones a pensar
8	voy a acabar
8	ibas a agarrar
8	voy a ir
8	voy a este hacer
8	voy a vender
8	voy a vender
8	voy a esperar
8	voy a jugar
8	voy a hacer
8	voy a poner
8	voy a estar
8	vamos a jugar
8	pongo a hacer
8	vas a hacer
8	vino a buscarme
8	vamos a hacerla
8	voy a reprochar
8	voy a ir
8	fui a ver
8	llegué a ver
8	vamos a levantar
8	vamos a preocuparnos
8	vamos a seguir viviendo
8	íbamos a tener
8	íbamos a estar este pagando
8	vamos a ver
8	vamos a entrarle
8	vamos a encajarnos
8	vamos a aventarnos
8	voy a hacer
8	voy a hacer
8	llegué a dar
8	vas a querer
8	vas a respetar
8	llegas a casar
8	vamos a tratar
8	se pongan ustedes a merendar
8	voy a ser
8	pongo a platicar
8	voy a decir
8	vamos a practicar
8	voy a practicar
8	voy a practicar
8	vamos a comer
8	dedicando a hacer
8	empecé a vivir
8	empecé a trabajar
8	fui a repartirlas
8	empecé a hacer
8	entré a trabajar
8	íbamos a vivir
8	voy a tener
8	vamos a borrar
8	vuelvo a hacer
8	empiezo a meter
8	acostumbro a meter
8	empiezo a trabajar
8	vuelvo a hablar?
8	vas a desprender
8	vas a partir
8	vas a querer
8	vas a hacer
8	voy a cobrar?
8	voy a llevar
8	voy a terminar
8	voy a echarme
8	vete a hacer
8	habíamos ido a comprar
8	empecé a andar
8	empecé a pagar
8	empecé a pagar
8	empecé a llorar
8	fuiste a comer
8	fui a comer
8	fui a comer
8	vayas a arrancar
8	vayas a comer
8	voy a tener
8	voy a empezar
8	vamos a pasar
8	voy a amarrar
8	voy a meter
8	vamos a salir
8	voy a  regresar
8	vas a ir
8	vamos a comer
8	vamos a comer
8	voy a demostrar
8	vas a meter
8	empiezo a platicar
8	voy a asaltar
8	vamos a dar
8	vamos a hacer
8	voy a bajar
8	vamos a ir
8	vamos a ir
8	voy a bajar
8	voy a soltar
8	voy a estar bajando
8	voy a ir a acostar
8	voy a ir
8	vamos a comprar
8	voy a estar diciendo
8	voy a estar viendo
8	voy a [comer
8	vamos a dar
8	vamos a invitarnos
8	voy a soltar
8	vas a traer
8	ir a acostar
8	irnos a comer
8	irnos a pasear
8	empecé a vivir
8	empecé a trabajar
8	íbamos a comer
8	voy a dejar
8	voy a decir
8	vamos a ver
8	voy a componer
8	vamos a ver
8	pongo a sacar
8	voy a pagar
7	estoy vendiendo
7	estábamos tan fregados
7	estuvimos arrimados
7	estábamos preparados
7	estábamos pagando
7	estoy diciendo
7	estamos casi esclavizados
7	estamos viviendo
7	estamos muy escasos
7	estamos constatando
7	sigo practicando
7	sigo trabajando
7	estábamos buscando
7	estoy juntando
7	estaríamos amolados
7	estoy trabajando
7	estoy todavía trabajando
7	estoy viendo
7	estoy cambiando
7	estoy viendo
7	sigues diciendo
7	sigo jugando
7	estoy ocupado
7	estamos ahí amotinando
7	estuvimos insistiendo
7	estábamos en bolita ahí cotorreando
7	estoy un rato conviviendo
7	estamos dedicando
7	estoy haciendo
7	estoy viendo
7	pienso terminar
7	estás trabajando
7	estoy trabajando
7	estoy batallando
7	estoy haciendo
7	estoy trabajando
7	estar haciendo
7	estamos levantando
7	estamos este fincando
7	seguíamos viviendo
7	estoy echando
7	estoy haciendo
7	estoy viendo
7	estamos hablando
7	estamos hablando
6	empezaron a entrar
6	empezaron a colonizar
6	empezaron a estar
6	empezaron a vender
6	empezó uno a buscar
6	empezó a levantarse
6	empezó a llegar
6	empezó a crecer
6	empezó a llegar
6	empiece uno a pedir
6	empieza uno a andar
6	empiezan a trabajar
6	empiezan a salir
6	empiezan a cantar
6	vuelve a cantar
6	empezó a portar
6	empezaron a aceptar
6	empezó a ver
6	metiéndose a romper
6	empezaron a escarbar
6	empezaron a
6	empezaban a meterse
6	empiezan a dar
6	empezaron a meter
6	empezaron a entrar
6	empiezan a agarrar
6	empezaron a quitar
6	empezaron a agarrar
6	empezar a aprender
6	empezar a embarrar
6	empezarle a batallar
6	comenzó a trazar
6	comienzan a agarrar
6	comienzan a amedrentarlos
6	empieza a entrar
6	comienzan a disgustar
6	comienzan uno a desvariar
6	pasaron a amolar
6	comienzan a hacer
6	empezó a subir
6	empezó a llegar
6	empezó a llamar
6	empezaba a subir
6	empezaba a saber
6	empieza como que a elevar
6	vuelven a llamar
6	empezó a golpear
6	empezó a decir
6	empezó a agarrar
6	empiezan a platicar
6	vuelve a agarrar
6	vuelve a agarrar
6	empezó a decir
6	empezó a trabajar
6	empiezan a hacer
5	está criado
5	esté encerado
5	esté pidiéndote
5	este agarrando
5	ha sido muy mentado
5	está repartiendo
5	está trabajando
5	está trabajando
5	ha ido progresando
5	ha ido progresando
5	ha ido progresando
5	está cuidando
5	está ella acomodando
5	estar completamente pelados
5	tiene almacenado
5	estar cuidando
5	está muy pesado
5	está este durmiendo
5	está durmiendo
5	está catalogado
5	está pensado
5	está ampliando
5	está viniendo
5	está retirado
5	está echando
5	va quedando
5	vaya quedando
5	vaya quedando
5	esté atendiendo
5	está guiando
5	está quedando
5	está convenciendo
5	ha sido ser
5	está fabricando
5	está labrando
5	está pirateando
5	estar atendiendo
5	está golpeado
5	está este asaltando
5	deja quito
5	está marcando
5	estar bajando
5	estar dedeando
5	esté presentado
5	está despegando
5	está/ despegando
5	está despegando
5	está grabando
5	estar limpiando
4	tienes que tirar
4	tienes que salir
4	tenías que bajar
4	tiene que ir
4	hay que saber
4	hay que ver
4	hay que saber
4	teníamos que comer
4	tengo que buscar
4	hay que ser
4	tienen que vivir
4	tiene que ser
4	hay que ver
4	tengo que ir
4	tienen que entrar
4	hay que recordar
4	hay que revolver
4	pasaba la gente comiendo eso
4	hay que conserva
4	tengo que sacar
4	hay que hacer
4	hay que echarle
4	hay que trabajar
4	tengo que pintar
4	tuve que arrancar
4	hay que tener
4	esta completamente abandonado
4	hay que saber
4	tenía que estar
4	tenido que arreglar
4	hay que ir
4	estar este metiéndose
4	poder este dormir
4	tiene que estar
4	tiene que sufrir
4	tenían que tener
4	tenía que haber
4	tiene que buscar
4	tienes que buscar
4	tenemos que pagar
4	hay que comprar
4	hay que comprar
4	hay que poner
4	tienes que ir
4	tengo que sacarle
4	tenían que ir
4	tenía que estar
4	teníamos que estar
4	hay que desalojar
4	tuvo que orillar
4	tuvo que entrar
4	tuvo que entrarle
4	tenían que pues llegar
4	tuvieron que entrarle
4	tenían que ir
4	tenía que ir
4	hay que ir a apoyar
4	hay que ir
4	tiene que aventar
4	tenemos que hacernos
4	tuvimos que ir
4	tendrá qué ser
4	tenía yo que sacar
4	hay que fortalecer
4	tengo que aceptarlos
4	teníamos que hacer
4	tuvo que darse
4	tuve que aplanar
4	teníamos que descubrir
4	tenían que quedar
4	tenía que hacer
4	tenía que [estar]
4	tenía que salirle
4	había que trabajar
4	tenía que disminuir
4	tenía que dar
4	tenga que ver
4	hay que saber
4	hay que saber
4	hay que cargar
4	tiene nada que ver
4	tienes que encontrarle
4	tienes que saber
4	tengo que llevar
4	hay que desarrollar
4	tengo que hacer
4	tiene que darse
4	tiene que convencer
4	tengo que buscarle
4	tener que llevar
4	haciendo suponer
4	tenías que pagar
4	tenías que este dar
4	tenía que pagar
4	tenía que pagar
4	tenía que bajar
4	tienes que llevar
4	dejar salir
4	tenemos que pagar
4	tenemos que dar
4	tienen que poner
4	tiene que cambiar
4	tengo que cuidar
4	tuvieron que coser
4	tenía que/ lavar
4	tenía que entrar
4	hay que estar
4	hay que guardar
4	tienen que pagar
4	tiene que dar
4	ya tiene dicho
4	tengo que salir
4	tienen que entregar
4	tienen que ser
3	acaban de echar
3	ha de ser
3	ha de ser
3	trato de acordarme
3	había yo acabado de pagar
3	debe de ser
3	acaba de pasar
3	acabo de decir
3	acabé de mencionar
3	debe de ser
3	deben de aceptar
3	debe de quitar
3	acabo de descrestar
3	deben de estar
3	deben de tener
3	deben de maltratar
3	deben de limpiar
3	deben de lavar
3	acabo de sacar
3	deben de ayudar
3	acababa yo de chocar
3	he de haber
3	debo de hacer
3	dejé de tomar
3	dejar de tomar
3	debo de tener
3	ha de haber
3	dejaron de jugar
3	debe de haber
3	debe de haber
3	tratan de buscar
3	llevo de conocerlos
3	llevo de conocerlos
3	terminar de labrar
3	acaba de entrar
3	han de cobrar
3	ha de tener
3	se debe de ganar
2	va a venirse
2	van a meter
2	van a meter
2	va a pertenecer
2	van a comer
2	viene a ser
2	van a pagar
2	va a hacer
2	va a cuidar
2	van a hacer
2	ve a ver
2	ha dado por ir a abrirlos
2	va a platicar
2	van a estar
2	va a hacer
2	van a decir
2	van a salir
2	van a salir
2	van a nacer
2	dan a amarrar
2	vienen a vigilarlo
2	vienen a barrer
2	va a haber
2	llega uno a cobrar
2	llegan a tomar
2	van a meter
2	van a venir
2	ponen unas señoras a vender
2	va a tener
2	va a venir
2	va a ser
2	ve a ayudarle
2	vienen a visitar
2	van a casar
2	empieza a estar
2	va a preguntar
2	va a luchar
2	llega a haber
2	llega a ver
2	lleguen a las de a hacer fraude
2	se va a ir urbanizando
2	se va a ir urbanizando
2	va a ir este componiendo
2	va a ir
2	van a quitar
2	va a ser
2	ponen a platicar
2	va a ser
2	va a llevar
2	se van este fortaleciendo
2	van a ayudar
2	viene a lavar
2	viene a planchar
2	va a convencer
2	va a quedar
2	va a terminar
2	va a quedar?
2	va a quedar
2	llega a salir
2	va a quedar
2	va a cumplir
2	van a parar
2	van a decir
2	van a parar
2	va a decir
2	va a agarrar
2	van a estar
2	va a cumplir
2	van a estar
2	van a venir
2	va a salir
2	va a ser
2	va a sacar
2	va a pasar
2	va a estar
2	va a costar
2	va a dar
1	volver a  tomar
1	venirse a tomar
1	volvieron a regresar
1	volvía a regresar
1	iban a bañar
1	fueron a echar
1	iba a entender
1	iba a traerle mandados
1	iba a limpiarle
1	iba a barrerle
1	iba a trabajar
1	ponía a trabajar
1	llegaba a ir
1	iban a hacer
1	fueron a pedir
1	llegué a ocupar
1	vino a crucificar
1	vino a morir
1	ir a visitar
1	iba a dar
1	iban a nacer
1	ponía a tirar
1	llegaron a romper
1	iba a empezar
1	fue a vendar
1	iba a armar
1	iba a decir
1	echaban a correr
1	alcanzó a aventar
1	echó a correr
1	fue a quedar
1	venía a dar
1	iban a tocarle
1	iba a jugar
1	iba a jugar
1	fue a conocer
1	llegó a entregar
1	iban a recibir
1	iban a tener
1	iban a crecer
1	iba a ser
1	llegó a vivir
1	llegamos a ganar
1	llegamos a ganar
1	llego a dejar
1	llego a morir
1	darle a ganar
1	llegase a ir
1	iba a trabajar
1	iban a tener
1	iban a llegar
1	fueras a apuntar
1	han llegado a trabajar
1	iba a manejar
1	iba a financiar
1	iban a hacer
1	venía a verlos
1	llegaba a ver
1	iba a quedar
1	pasaron a dar
1	iba a ser
1	iba a entrar
1	iba a sostener
1	iba a echar
1	iba a apoyar
1	iban a ir
1	iban a cargar
1	iba a plasmar
1	llegar a ser
1	llego a dar
1	ir a cobrar
1	entrar a trabajar
1	vino a vivir
1	fue a vivir
1	iba a trabajar
1	iba a visitar
1	pasaba a visitar
1	iban a quitar
1	iban a dar
1	iba a vender
1	iba a trabajar
1	llegado a ir
1	vino a ver
0	deja contarlos
0	van metiendo
0	van contagiando
0	va dando
0	va empezando
0	va empezando
0	van creciendo
0	va dando
0	va componiendo
0	va llegando
0	van viendo
0	va viendo
0	va entrando
0	vaya aceptando
0	va haciendo
0	va viendo
0	va haciendo
0	van haciendo
0	van siendo
0	van traumando
0	va uno traumando
0	van fortaleciendo
0	van viendo
0	van viendo
0	van este guiando
0	vayan acostumbrando
0	vaya dando
0	vaya agarrando
0	va dando
0	va convenciendo
0	va querer
0	va recomendando
0	va subiendo
0	van apretando
Silhouette Coefficient: 0.093
Number of clusters: 17

